// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OSApiInterface;

namespace OSApiInterface.Migrations
{
    [DbContext(typeof(EntityCoreContext))]
    [Migration("20190515161402_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OSApiInterface.Models.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DirectoryId");

                    b.Property<long>("Global");

                    b.Property<bool>("IsDirectory");

                    b.Property<string>("Name");

                    b.Property<bool>("Share");

                    b.Property<string>("Type");

                    b.HasKey("Id")
                        .HasName("pk_file_entities");

                    b.HasIndex("DirectoryId")
                        .HasName("idx_fe_directory");

                    b.HasIndex("Name")
                        .HasName("idx_fe_name");

                    b.ToTable("file_entities");

                    b.HasData(
                        new { Id = -1, Global = 0L, IsDirectory = false, Name = "/", Share = true, Type = "folder" }
                    );
                });

            modelBuilder.Entity("OSApiInterface.Models.FileEntity", b =>
                {
                    b.HasOne("OSApiInterface.Models.FileEntity", "Directory")
                        .WithMany("Children")
                        .HasForeignKey("DirectoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
