// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zk.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from zk.proto</summary>
public static partial class ZkReflection {

  #region Descriptor
  /// <summary>File descriptor for zk.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ZkReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgh6ay5wcm90byIwCgZTZXJ2ZXISFAoMem1xX3RjcF9wb3J0GAEgASgJEhAK",
          "CHptcV9ob3N0GAIgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Server), global::Server.Parser, new[]{ "ZmqTcpPort", "ZmqHost" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Server : pb::IMessage<Server> {
  private static readonly pb::MessageParser<Server> _parser = new pb::MessageParser<Server>(() => new Server());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Server> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ZkReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server(Server other) : this() {
    zmqTcpPort_ = other.zmqTcpPort_;
    zmqHost_ = other.zmqHost_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server Clone() {
    return new Server(this);
  }

  /// <summary>Field number for the "zmq_tcp_port" field.</summary>
  public const int ZmqTcpPortFieldNumber = 1;
  private string zmqTcpPort_ = "";
  /// <summary>
  /// addr for zmq
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ZmqTcpPort {
    get { return zmqTcpPort_; }
    set {
      zmqTcpPort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "zmq_host" field.</summary>
  public const int ZmqHostFieldNumber = 2;
  private string zmqHost_ = "";
  /// <summary>
  /// host for zmq
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ZmqHost {
    get { return zmqHost_; }
    set {
      zmqHost_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Server);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Server other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ZmqTcpPort != other.ZmqTcpPort) return false;
    if (ZmqHost != other.ZmqHost) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ZmqTcpPort.Length != 0) hash ^= ZmqTcpPort.GetHashCode();
    if (ZmqHost.Length != 0) hash ^= ZmqHost.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ZmqTcpPort.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ZmqTcpPort);
    }
    if (ZmqHost.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ZmqHost);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ZmqTcpPort.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ZmqTcpPort);
    }
    if (ZmqHost.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ZmqHost);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Server other) {
    if (other == null) {
      return;
    }
    if (other.ZmqTcpPort.Length != 0) {
      ZmqTcpPort = other.ZmqTcpPort;
    }
    if (other.ZmqHost.Length != 0) {
      ZmqHost = other.ZmqHost;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ZmqTcpPort = input.ReadString();
          break;
        }
        case 18: {
          ZmqHost = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
